// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrV63j0IC1Xf31BBAuCc7ocNbadbVretc',
    appId: '1:954241809959:web:0753cc370300122f8a1802',
    messagingSenderId: '954241809959',
    projectId: 'cerd-2c2d7',
    authDomain: 'cerd-2c2d7.firebaseapp.com',
    storageBucket: 'cerd-2c2d7.firebasestorage.app',
    measurementId: 'G-84E4W11X1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ6JO4vMaEuOrygFjEkbtv_YZixD3SlvQ',
    appId: '1:954241809959:android:1e63b39802c3b7228a1802',
    messagingSenderId: '954241809959',
    projectId: 'cerd-2c2d7',
    storageBucket: 'cerd-2c2d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkstsHBe-a3bE1A6S2qiey0Dqcne3ZRro',
    appId: '1:954241809959:ios:9079bc479860eb548a1802',
    messagingSenderId: '954241809959',
    projectId: 'cerd-2c2d7',
    storageBucket: 'cerd-2c2d7.firebasestorage.app',
    iosBundleId: 'com.example.fypSourceCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkstsHBe-a3bE1A6S2qiey0Dqcne3ZRro',
    appId: '1:954241809959:ios:9079bc479860eb548a1802',
    messagingSenderId: '954241809959',
    projectId: 'cerd-2c2d7',
    storageBucket: 'cerd-2c2d7.firebasestorage.app',
    iosBundleId: 'com.example.fypSourceCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrV63j0IC1Xf31BBAuCc7ocNbadbVretc',
    appId: '1:954241809959:web:4a07aadfaae3504a8a1802',
    messagingSenderId: '954241809959',
    projectId: 'cerd-2c2d7',
    authDomain: 'cerd-2c2d7.firebaseapp.com',
    storageBucket: 'cerd-2c2d7.firebasestorage.app',
    measurementId: 'G-XZ0SLDZB2P',
  );
}
