// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEc4Lc11eEEdv8RxS3jKY1U-MTs0ZFRLM',
    appId: '1:691368195248:web:35cdb49c32614cb4e97775',
    messagingSenderId: '691368195248',
    projectId: 'muhafiz-afd88',
    authDomain: 'muhafiz-afd88.firebaseapp.com',
    storageBucket: 'muhafiz-afd88.firebasestorage.app',
    measurementId: 'G-8P6B9F3EYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDctCEFDBDxmTCutSSdTWCFqEpUZimd-uE',
    appId: '1:691368195248:android:b8788769a3c2687ce97775',
    messagingSenderId: '691368195248',
    projectId: 'muhafiz-afd88',
    storageBucket: 'muhafiz-afd88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNq33dn74rVfuUS0E-qZkDL6tZDUUzAHo',
    appId: '1:691368195248:ios:00bccab1fda74b7ce97775',
    messagingSenderId: '691368195248',
    projectId: 'muhafiz-afd88',
    storageBucket: 'muhafiz-afd88.firebasestorage.app',
    iosBundleId: 'com.example.fypSourceCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNq33dn74rVfuUS0E-qZkDL6tZDUUzAHo',
    appId: '1:691368195248:ios:00bccab1fda74b7ce97775',
    messagingSenderId: '691368195248',
    projectId: 'muhafiz-afd88',
    storageBucket: 'muhafiz-afd88.firebasestorage.app',
    iosBundleId: 'com.example.fypSourceCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEc4Lc11eEEdv8RxS3jKY1U-MTs0ZFRLM',
    appId: '1:691368195248:web:c1fd9a877c2befe1e97775',
    messagingSenderId: '691368195248',
    projectId: 'muhafiz-afd88',
    authDomain: 'muhafiz-afd88.firebaseapp.com',
    storageBucket: 'muhafiz-afd88.firebasestorage.app',
    measurementId: 'G-J8P34T89T6',
  );
}
